name: industrial_ci

on: [push, pull_request]

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [noetic, humble, jazzy, rolling]
        ROS_REPO: [testing, main]
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{ toJSON(matrix) }}